spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8881
          predicates:
            - Path=/users/**
        - id: books-service
          uri: http://localhost:8181
          predicates:
            - Path=/books/**
        - id: order-service
          uri: http://localhost:7080
          predicates:
            - Path=/orders/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
